/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package study.assistant;

import study.assistant.signupp.signup;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import static study.assistant.StudyAssistant.prog;

/**
 *
 * @author rami
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
      /*  
        ImageIcon icon =new ImageIcon (getClass().getResource("st.jpg"));
        Image img=icon.getImage().getScaledInstance(900, 900, Image.SCALE_SMOOTH);
        jLabel6.setIcon(icon);
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        loginLBL = new javax.swing.JLabel();
        loginBTN = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        userTF = new javax.swing.JTextField();
        userLBL = new javax.swing.JLabel();
        passLBL = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        signUpLBL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        checkLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLBL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        loginLBL.setForeground(new java.awt.Color(254, 254, 254));
        loginLBL.setText("Login");
        loginLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLBLMouseClicked(evt);
            }
        });
        jPanel1.add(loginLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        loginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Drawing(1).png"))); // NOI18N
        loginBTN.setText("jLabel6");
        loginBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBTNMouseClicked(evt);
            }
        });
        jPanel1.add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 220, 70));

        jSeparator2.setBackground(new java.awt.Color(177, 8, 55));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 170, 20));

        userTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userTF.setForeground(new java.awt.Color(177, 172, 172));
        userTF.setText("example@email.com");
        userTF.setBorder(null);
        userTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTFFocusLost(evt);
            }
        });
        userTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTFMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userTFMouseExited(evt);
            }
        });
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        jPanel1.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 280, 30));

        userLBL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        userLBL.setText("username");
        jPanel1.add(userLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        passLBL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        passLBL.setText("password");
        jPanel1.add(passLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        passTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passTF.setForeground(new java.awt.Color(148, 148, 148));
        passTF.setText("password12345");
        passTF.setBorder(null);
        passTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTFFocusLost(evt);
            }
        });
        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });
        jPanel1.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 280, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 139, 234));
        jLabel4.setText("forgot my password ");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tlwg Typist", 0, 48)); // NOI18N
        jLabel5.setText("Study Assistant");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 510, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/1.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 480, -1));

        jSeparator1.setBackground(new java.awt.Color(177, 8, 55));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 170, 20));

        signUpLBL.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        signUpLBL.setForeground(new java.awt.Color(55, 139, 234));
        signUpLBL.setText("Sign up ");
        signUpLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLBLMouseClicked(evt);
            }
        });
        jPanel1.add(signUpLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tlwg Typist", 0, 48)); // NOI18N
        jLabel9.setText("Login ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 250, 110));

        checkLBL.setBackground(new java.awt.Color(255, 255, 255));
        checkLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkLBL.setForeground(new java.awt.Color(188, 16, 21));
        checkLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(checkLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 420, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void userTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTFMouseClicked

        // TODO add your handling code here:
        
    }//GEN-LAST:event_userTFMouseClicked

    private void userTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTFFocusGained
        // TODO add your handling code here:
        if(userTF.getText().equals("example@email.com")){
          userTF.setText("");
          userTF.setForeground(Color.black);
        }
        
   
    }//GEN-LAST:event_userTFFocusGained

    private void userTFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTFMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFMouseExited

    private void userTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTFFocusLost
if(userTF.getText().equals("")){
     userTF.setText("example@email.com");
     userTF.setForeground(new Color(148,148,148));
        } 

        
    }//GEN-LAST:event_userTFFocusLost

    private void passTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTFFocusGained
        // TODO add your handling code here:
        if(passTF.getText().equals("password12345")){
                   passTF.setText("");
                   passTF.setForeground(Color.black);
        }

    }//GEN-LAST:event_passTFFocusGained

    private void passTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTFFocusLost
        // TODO add your handling code here
        
        if(passTF.getText().equals("")){
             passTF.setText("password12345");
             passTF.setForeground(new Color(148,148,148));
        
        } 

    }//GEN-LAST:event_passTFFocusLost

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTFActionPerformed

    private void signUpLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLBLMouseClicked
        // TODO add your handling code here:
        
       signup s=new signup();
       s.setLocationRelativeTo(this);
       s.setDefaultCloseOperation(HIDE_ON_CLOSE);
       s.setVisible(true);
       
    }//GEN-LAST:event_signUpLBLMouseClicked

    private void loginBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTNMouseClicked
        // TODO add your handling code here:
          String username= userTF.getText();
        String password= new String(passTF.getPassword());
        
        if(checkPassword(username,password)){
        prog.home=new home();
        prog.login.dispose();
        prog.home.setTitle("home");
        prog.home.setLocationRelativeTo(this);
        prog.home.setVisible(true);
        }
        else{
        if(userTF.getText().equals("")||new Color(148,148,148).equals(userTF.getForeground()))
        { 
            checkLBL.setText("Please fill the username and password field");
            return;
        }
        if(new String(passTF.getPassword()).equals("")||new Color(148,148,148).equals(passTF.getForeground()))
        {
        checkLBL.setText("Please fill the username and password field");
            return;
        }
      
        if(checkUsername(username)){
            checkLBL.setText("Username not found");
            
            return;}
        if(!checkPassword(username,password)){
            checkLBL.setText("Password and username don't match");
            return;}
        
        }
    }//GEN-LAST:event_loginBTNMouseClicked

    private void loginLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLBLMouseClicked
        // TODO add your handling code here:
        String username= userTF.getText();
        String password= new String(passTF.getPassword());
        
        if(checkPassword(username,password)){
        prog.home=new home();
        prog.login.dispose();
        prog.home.setTitle("home");
        prog.home.setLocationRelativeTo(this);
        prog.home.setVisible(true);
        }
        else{
        if(userTF.getText().equals("")||new Color(148,148,148).equals(userTF.getForeground()))
        { 
            checkLBL.setText("Please fill the username and password field");
            return;
        }
        if(new String(passTF.getPassword()).equals("")||new Color(148,148,148).equals(passTF.getForeground()))
        {
        checkLBL.setText("Please fill the username and password field");
            return;
        }
      
        if(checkUsername(username)){
            checkLBL.setText("Username not found");
            
            return;}
        if(!checkPassword(username,password)){
            checkLBL.setText("Password and username don't match");
            return;}
        
        }
    }//GEN-LAST:event_loginLBLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    //to be modified
    public boolean checkUsername(String username){
        return true;
    }
    //to be modified
    public boolean checkPassword(String username,String password){
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkLBL;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginBTN;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JLabel passLBL;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JLabel signUpLBL;
    private javax.swing.JLabel userLBL;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
