/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package study.assistant.signupp;

/**
 *
 * @author rami
 */
public class ac extends javax.swing.JPanel {

    /**
     * Creates new form ac
     */
    public ac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ac = new javax.swing.JPanel();
        uniNameTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        ac.setBackground(new java.awt.Color(254, 254, 254));

        uniNameTF.setBackground(new java.awt.Color(254, 254, 254));
        uniNameTF.setForeground(new java.awt.Color(149, 135, 135));
        uniNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniNameTFActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel11.setText("uni name");

        javax.swing.GroupLayout acLayout = new javax.swing.GroupLayout(ac);
        ac.setLayout(acLayout);
        acLayout.setHorizontalGroup(
            acLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(uniNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        acLayout.setVerticalGroup(
            acLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(acLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(uniNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uniNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniNameTFActionPerformed

    public boolean checkEmptyFields(){
        if(uniNameTF.getText().equals(""))
            return true;

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ac;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JTextField uniNameTF;
    // End of variables declaration//GEN-END:variables
}
