/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package study.assistant.signupp;

import database.Puser;
import java.awt.Color;
import static java.sql.JDBCType.NULL;
import study.assistant.signupp.ac;
import study.assistant.signupp.non;
import study.assistant.signupp.st;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author rami
 */

public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    st a;
    non b;
    ac c;
    public signup() {
        initComponents();
        
     
a=new st();
b=new non();
c=new ac();

     main.removeAll();
        main.revalidate();
        main.repaint();
        main.add(a);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        lNameTF = new javax.swing.JTextField();
        passConfirmTF = new javax.swing.JPasswordField();
        passwordTF = new javax.swing.JPasswordField();
        gender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        signupLBL = new javax.swing.JLabel();
        signupBTN = new javax.swing.JLabel();
        acctTypeCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        usernameCheckLBL = new javax.swing.JLabel();
        checkLBL = new javax.swing.JLabel();
        passwordCheckLBL = new javax.swing.JLabel();
        birthdateJDC = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setForeground(new java.awt.Color(12, 16, 12));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(149, 135, 135));
        usernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTFFocusLost(evt);
            }
        });
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 170, 30));

        lNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lNameTF.setForeground(new java.awt.Color(149, 135, 135));
        lNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(lNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 120, 30));

        passConfirmTF.setForeground(new java.awt.Color(149, 135, 135));
        passConfirmTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passConfirmTFFocusLost(evt);
            }
        });
        jPanel1.add(passConfirmTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 328, 160, 30));

        passwordTF.setForeground(new java.awt.Color(149, 135, 135));
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 273, 160, 30));

        gender.setBackground(new java.awt.Color(254, 254, 254));
        gender.setForeground(new java.awt.Color(12, 11, 21));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, 20));

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel2.setText("Last name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel5.setText("Birth date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel6.setText("account type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, -1));

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        main.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 430, 123));

        signupLBL.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        signupLBL.setForeground(new java.awt.Color(254, 254, 254));
        signupLBL.setText("signup");
        signupLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLBLMouseClicked(evt);
            }
        });
        jPanel1.add(signupLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 50, -1));

        signupBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Drawing(1).png"))); // NOI18N
        signupBTN.setText("jLabel6");
        signupBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupBTNMouseClicked(evt);
            }
        });
        jPanel1.add(signupBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 220, 80));

        acctTypeCB.setBackground(new java.awt.Color(254, 254, 254));
        acctTypeCB.setForeground(new java.awt.Color(12, 11, 21));
        acctTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Acamemic instructor", "non-academic instructor" }));
        acctTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctTypeCBActionPerformed(evt);
            }
        });
        jPanel1.add(acctTypeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 180, 30));

        jLabel9.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel9.setText("confirm password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 333, 140, -1));

        jLabel10.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel10.setText("First name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        fNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fNameTF.setForeground(new java.awt.Color(149, 135, 135));
        jPanel1.add(fNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 30));

        usernameCheckLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(usernameCheckLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 124, 140, 20));

        checkLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkLBL.setForeground(new java.awt.Color(188, 16, 21));
        jPanel1.add(checkLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 250, 30));

        passwordCheckLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordCheckLBL.setForeground(new java.awt.Color(188, 16, 21));
        jPanel1.add(passwordCheckLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 324, 170, 30));
        jPanel1.add(birthdateJDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void acctTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctTypeCBActionPerformed
        // TODO add your handling code here:
        
        int x = acctTypeCB.getSelectedIndex();
        
        switch(x){
            case 0 :
        main.removeAll();
        main.revalidate();
        main.repaint();
        main.add(a);
        break;
        
            case 1 :
        main.removeAll();
        main.revalidate();
        main.repaint();
        main.add(c);
        break;
            case 2 :
        main.removeAll();
        main.revalidate();
        main.repaint();
        main.add(b);
        
        break;
        }
    }//GEN-LAST:event_acctTypeCBActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void lNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTFActionPerformed

    private void usernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFFocusLost
        // TODO add your handling code here:
        if(!usernameTF.getText().equals("")){
            if (!checkUsername(usernameTF.getText())) {
                usernameCheckLBL.setForeground(new Color(188,16,21));
                usernameCheckLBL.setText("username already exists");
            }
            else{
                usernameCheckLBL.setForeground(new Color(12,166,33));
                usernameCheckLBL.setText("username valid");
            }
        }
    }//GEN-LAST:event_usernameTFFocusLost

    private void signupBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBTNMouseClicked
        // TODO add your handling code here:
        if(checkEmptyFields()){
            checkLBL.setText("Please fill all the fields");
        }
        else if (!checkUsername(usernameTF.getText())) {
            checkLBL.setText("Please choose a valid username");
            }
        else if(checkPasswordConfirmation())
            checkLBL.setText("The passwords don't match");
        else
        {
            //insert the row to the table
        }
    }//GEN-LAST:event_signupBTNMouseClicked

    private void signupLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLBLMouseClicked
        // TODO add your handling code here:
       if(checkEmptyFields()){
            checkLBL.setText("Please fill all the fields");
        }
        else if (!checkUsername(usernameTF.getText())) {
            checkLBL.setText("Please choose a valid username");
            }
        else if(checkPasswordConfirmation())
            checkLBL.setText("The passwords don't match");
        else
        {
            
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("study_assistant11PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            Puser user=new Puser();
            user.setFname(fNameTF.getText());
            user.setLname(lNameTF.getText());
            user.setUsername(usernameTF.getText());
            user.setBirthdate(birthdateJDC.getDate());
            
            
            char g;
          if(  gender.getSelectedIndex()==0)
          g='M';
          else g='F';
          
            user.setGender(g);
            user.setPassword(new String (passwordTF.getPassword()));
            user.setType((String)acctTypeCB.getSelectedItem());
            
           if("Student".equals(user.getType())){
             user.setClass1((String) a.classCM.getSelectedItem());
             user.setUniName(a.uniNameTF.getText());
             user.setUniId(a.uniIdTF.getText());
           }
           if("Acamemic instructo".equals(user.getType())){
               user.setUnivirsity(c.uniNameTF.getText());
//           
           }
           if("non-academic instructor".equals(user.getType())){
               user.setJobTitle(b.jTitleTF.getText());
           
           }
           em.persist(user);
           em.getTransaction().commit();
           
           em.close();
           emf.close();
            
           
            
            
        }
       
       
       this.dispose();
       
    }//GEN-LAST:event_signupLBLMouseClicked

    private void passConfirmTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passConfirmTFFocusLost
        // TODO add your handling code here:
        if(checkPasswordConfirmation()){
            passwordCheckLBL.setText("Passwords don't match");
            passwordCheckLBL.setForeground(new Color(188,16,21));
        }
        else{
            passwordCheckLBL.setText("Passwords match");
            passwordCheckLBL.setForeground(new Color(12,166,33));
        }
    }//GEN-LAST:event_passConfirmTFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }
    //to be modified
    public boolean checkUsername(String username){
        return true;
    }
    
    public boolean checkEmptyFields(){
        if(fNameTF.getText().equals(""))
            return true;
        if(lNameTF.getText().equals(""))
            return true;
        if(usernameTF.getText().equals(""))
            return true;
        if(passwordTF.getText().equals(""))
            return true;
        if(passConfirmTF.getText().equals(""))
            return true;
        if(birthdateJDC.getDate()==null)
            return true;
       int i=acctTypeCB.getSelectedIndex();
       switch(i){
           case 0:if (a.checkEmptyFields()) {
                   return true;
               }
             break;
           case 1:if(c.checkEmptyFields())
               return true;
             break;
           case 2:if(b.checkEmptyFields())
               return true;
             break;
       }
       return false;
    }
    
    public boolean checkPasswordConfirmation(){
        return !new String(passwordTF.getPassword()).equals(new String(passConfirmTF.getPassword()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acctTypeCB;
    private com.toedter.calendar.JDateChooser birthdateJDC;
    private javax.swing.JLabel checkLBL;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField passConfirmTF;
    private javax.swing.JLabel passwordCheckLBL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel signupBTN;
    private javax.swing.JLabel signupLBL;
    private javax.swing.JLabel usernameCheckLBL;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
