/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar;

import database.Event;
import java.math.BigInteger;
import java.util.Calendar;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import static study.assistant.StudyAssistant.prog;
import study.assistant.home;

/**
 *
 * @author masri
 */
public class NotificationForm extends javax.swing.JFrame {

    /**
     * Creates new form NotificationForm
     */
    public NotificationForm(Event e) {
        initComponents();
        this.e=e;
        this.setResizable(false);
        this.setTitle("Notification time");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private NotificationForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nTimeCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        addTextLbl = new javax.swing.JLabel();
        addLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nTimeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 day before", "2 days before", "3 days before", "1 week before ", "2 weeks before" }));
        jPanel1.add(nTimeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 40, 173, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("When?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 38, 52, 31));

        addTextLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addTextLbl.setForeground(new java.awt.Color(255, 255, 255));
        addTextLbl.setText("Add");
        addTextLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTextLblMouseClicked(evt);
            }
        });
        jPanel1.add(addTextLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        addLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Drawing(1).png"))); // NOI18N
        addLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLblMouseClicked(evt);
            }
        });
        jPanel1.add(addLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLblMouseClicked
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("gitPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        Event ev = em.find(Event.class, e.getEid());
        home.user.getEventCollection().remove(e);
        
        updateNTime();
        ev.setNTime(e.getNTime());
        ev.setNF(BigInteger.ONE);
        em.persist(ev);
        home.user.getEventCollection().add(ev);

        em.getTransaction().commit();
        
        em.close();
        emf.close();
        prog.home.alterpanel.removeAll();
        prog.home.alterpanel.revalidate();
        prog.home.alterpanel.repaint();
        prog.home.alterpanel.add(new CalendarPnl());
        this.dispose();
    }//GEN-LAST:event_addLblMouseClicked

    private void addTextLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTextLblMouseClicked
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("gitPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        Event ev = em.find(Event.class, e.getEid());
        home.user.getEventCollection().remove(e);
        
        updateNTime();
        ev.setNTime(e.getNTime());
        ev.setNF(BigInteger.ONE);
        em.persist(ev);
        home.user.getEventCollection().add(ev);

        em.getTransaction().commit();
        
        em.close();
        emf.close();
        prog.home.alterpanel.removeAll();
        prog.home.alterpanel.revalidate();
        prog.home.alterpanel.repaint();
        prog.home.alterpanel.add(new CalendarPnl());
        this.dispose();
    }//GEN-LAST:event_addTextLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotificationForm().setVisible(true);
            }
        });
    }
    public void updateNTime(){
        Calendar c=Calendar.getInstance();
        e.setNF(BigInteger.ONE);
        switch(nTimeCB.getSelectedIndex()){
                case 0:c.set(Calendar.DAY_OF_YEAR,c.get(Calendar.DAY_OF_YEAR)-1);
                       break;
                case 1:c.set(Calendar.DAY_OF_YEAR,c.get(Calendar.DAY_OF_YEAR)-2);
                       break;
                case 2:c.set(Calendar.DAY_OF_YEAR,c.get(Calendar.DAY_OF_YEAR)-3);
                       break;
                case 3:c.set(Calendar.DAY_OF_YEAR,c.get(Calendar.DAY_OF_YEAR)-7);
                       break;
                case 4:c.set(Calendar.DAY_OF_YEAR,c.get(Calendar.DAY_OF_YEAR)-3);
                       break;
            }
            e.setNTime(c.getTime());
}
    private Event e;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLbl;
    private javax.swing.JLabel addTextLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> nTimeCB;
    // End of variables declaration//GEN-END:variables
}
