/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extrapanels;

import database.Event;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;

/**
 *
 * @author masri
 */
public class EventPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventPanel
     */
    public EventPanel(Event e) {
        initComponents();
        updatePanel(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNameLbl = new javax.swing.JLabel();
        eTimeLbl = new javax.swing.JLabel();
        eNTimeLbl = new javax.swing.JLabel();
        eDescLbl = new javax.swing.JLabel();
        notificationLbl = new javax.swing.JLabel();
        settingsLbl = new javax.swing.JLabel();

        eNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eNameLbl.setText("Circut First Exam");

        eTimeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eTimeLbl.setText("Nov 13 at 12:30");

        eNTimeLbl.setText("Notify me 2 days before");

        eDescLbl.setText("The exam is until section 12.3");
        eDescLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        notificationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/notifications-button-24.png"))); // NOI18N

        settingsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/settings-work-tool-24.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eNameLbl)
                    .addComponent(eDescLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNTimeLbl)
                    .addComponent(eTimeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationLbl)
                    .addComponent(settingsLbl))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNameLbl)
                    .addComponent(notificationLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eTimeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eNTimeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(eDescLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(settingsLbl)))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void updatePanel(Event e){
        eNameLbl.setText(e.getName());
        eDescLbl.setText(e.getDescription());
        GregorianCalendar c=new GregorianCalendar();
        c.setTime(e.getTime());
        String time="",nTime="";
        eTimeLbl.setText(time);
        if(e.getNF().equals("1")){//to be changed
            notificationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/turn-notifications-on-button-24.png"))); // NOI18N
            eNTimeLbl.setText(nTime);
        }
        else{
            notificationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/notifications-button-24.png")));
            eNTimeLbl.setText("");
        }
        
    }
    String MONTHS[]={"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eDescLbl;
    private javax.swing.JLabel eNTimeLbl;
    private javax.swing.JLabel eNameLbl;
    private javax.swing.JLabel eTimeLbl;
    private javax.swing.JLabel notificationLbl;
    private javax.swing.JLabel settingsLbl;
    // End of variables declaration//GEN-END:variables
}
